### ISSUE TITLE
Advance voting

### ISSUE THREAD

**Issue by danylmc** [ellisp/nzelect#12]
Hi Peter - Thanks for creating this resource - it's brilliant. Do you have any plans to include advance voting data in the nzelect dataset?

**Comment by ellisp** [comment]
maybe.... priority is to get all the historical polling location data back to 2002, then of course the 2017 results.  The advance votes and other special votes are still in the polling place data, so they're not actually missing, it might be a matter of labelling them better.

**Comment by ellisp** [comment]
Turns out these were always there, the voting_place is described with names like:

```
        approx_location                                                       voting_place
1              Woodbury                                  Ordinary Votes BEFORE polling day
2              Woodbury                                   Special Votes BEFORE polling day
```
So we can see:
```R
library(dplyr)
library(ggplot2)
library(nzelect)
library(forcats)
library(scales)

nzge %>%
    filter(grepl("BEFORE", voting_place, ignore.case = TRUE)) %>%
    filter(voting_type == "Candidate") %>%
    mutate(party = fct_reorder(party, votes),
           party = fct_lump(party, 6)) %>%
    group_by(party, election_year) %>%
    summarise(votes = sum(votes)) %>%
    ggplot(aes(x = votes, y = party)) +
    facet_wrap(~election_year) +
    geom_point() +
    scale_x_continuous("Votes before the election", label = comma)
```
![image](https://user-images.githubusercontent.com/5740570/31144118-31f5ee62-a8dc-11e7-82c5-435a0e4e635d.png)
